### PR TITLE
BUG: Fix nubes-boot loop with private IP

### LINKED ISSUE #126: nubes-bootcontext.sh stuck in loop
**Describe the bug**
When building a VM on a private network the nubes-bootcontext.sh script gets stuck in an indefinite loop. This causes the update_cloud_users.sh script to not run and users do not get added to the VMs. This stops users from accessing their VM.

**To Reproduce**
1. Build VM with ubuntu-noble-24.04-nogui image
2. Attempt to SSH in as FEDID, not working
3. SSH in as cloud user
4. See no users in `ls -la /home`

**Expected behavior**
When a VM has a non 130 / 172 IP the script should skip the hostname change and continue to run.

**Screenshots**
See https://github.com/stfc/cloud-image-builders/blob/main/os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh

**Details (please complete the following information):**
 - Image Name: e.g. ubuntu-noble-24.04-nogui
 - Image ID 0aac6e05-e21a-4f7f-9c01-8481d7d105c7
 - VM ID N/A
 - JIRA Ticket Ref: [CLDSCRM-3777](https://stfc.atlassian.net/browse/CLDSCRM-3777)

**Additional context**
This is likely to be seen on any OS image. Ubuntu 22 / 24 and Rocky 8 / 9 / AQ

### PR DESCRIPTION
**Pull request by khalford**
Add a break to the while loop when the IP is not 130 or 172 and limit to 3 retries when changing hostname before continuing.

See commit message.

Resolves #126

### CODE REVIEW

**Review by gmatthews20 — DISMISSED** [review]

File: os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh [hunk 1]
```diff
@@ -14,8 +16,14 @@ do
         else
             hostname="networktest";
         fi;
+        sleep 5s
```
Comment (DavidFair) [inline os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh:19]: I think we should change the hostname (if it fails to lookup) to `hostname-missing` instead of `networktest`

Else we'll potentially have users going "why is my machine a `networktest` machine"

Comment (khalford) [reply os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh:19]: It won't set it to "networktest". It will leave it as the OpenStack VM name which is set by cloud init

File: os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh [hunk 2]
```diff
@@ -1,10 +1,12 @@
 #!/bin/bash
 
+set -x
```
Comment (DavidFair) [inline os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh]: Just noticed, this should be set to `set -euxo pipefail`

As we should always fail noisy instead of taking potentially corrupt data and making things worse

**Review by DavidFair — CHANGES_REQUESTED** [review]

File: os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh (hunk 2 above)
Comment (khalford) [reply os_builders/roles/nubes_bootcontext/files/nubes-bootcontext.sh]: :+1:

**Review by DavidFair — APPROVED** [review]

**Review by gmatthews20 — APPROVED** [review]
